### ISSUE TITLE
When MCMC run with CPL, w0 can not cross -1 

### ISSUE THREAD

**Issue by lighink** [CobayaSampler/cobaya#143]
Hi all, 

When I use cobaya to run CPL model with Planck+BAO+Pantheon, it seems that w0 is always lager than -1. I use camb as the theory code. Anyone checked this? My input yaml file is as follows.

```
theory:
  camb:
    extra_args:
      bbn_predictor: PArthENoPE_880.2_standard.dat
      halofit_version: mead
      lens_potential_accuracy: 1
      nnu: 3.046
      num_massive_neutrinos: 1
      theta_H0_range:
      - 20
      - 100
likelihood:
  bao.sdss_dr12_consensus_bao: null
  bao.sdss_dr7_mgs: null
  bao.sixdf_2011_bao: null
  planck_2018_highl_plik.TTTEEE: null
  planck_2018_lensing.clik: null
  planck_2018_lowl.EE: null
  planck_2018_lowl.TT: null
  sn.pantheon: null
params:
  A:
    derived: 'lambda As: 1e9*As'
    latex: 10^9 A_\mathrm{s}
  As:
    latex: A_\mathrm{s}
    value: 'lambda logA: 1e-10*np.exp(logA)'
  DHBBN:
    derived: 'lambda DH: 10**5*DH'
    latex: 10^5 \mathrm{D}/\mathrm{H}
  H0:
    latex: H_0
    max: 100
    min: 20
  YHe:
    latex: Y_\mathrm{P}
  Y_p:
    latex: Y_P^\mathrm{BBN}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
  clamp:
    derived: 'lambda As, tau: 1e9*As*np.exp(-2*tau)'
    latex: 10^9 A_\mathrm{s} e^{-2\tau}
  cosmomc_theta:
    derived: false
    value: 'lambda theta_MC_100: 1.e-2*theta_MC_100'
  logA:
    drop: true
    latex: \log(10^{10} A_\mathrm{s})
    prior:
      max: 3.91
      min: 1.61
    proposal: 0.001
    ref:
      dist: norm
      loc: 3.05
      scale: 0.001
  mnu: 0.06
  ns:
    latex: n_\mathrm{s}
    prior:
      max: 1.2
      min: 0.8
    proposal: 0.002
    ref:
      dist: norm
      loc: 0.965
      scale: 0.004
  ombh2:
    latex: \Omega_\mathrm{b} h^2
    prior:
      max: 0.1
      min: 0.005
    proposal: 0.0001
    ref:
      dist: norm
      loc: 0.0224
      scale: 0.0001
  omch2:
    latex: \Omega_\mathrm{c} h^2
    prior:
      max: 0.99
      min: 0.001
    proposal: 0.0005
    ref:
      dist: norm
      loc: 0.12
      scale: 0.001
  omegam:
    latex: \Omega_\mathrm{m}
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  rdrag:
    latex: r_\mathrm{drag}
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  sigma8:
    latex: \sigma_8
  tau:
    latex: \tau_\mathrm{reio}
    prior:
      max: 0.8
      min: 0.01
    proposal: 0.003
    ref:
      dist: norm
      loc: 0.055
      scale: 0.006
  theta_MC_100:
    drop: true
    latex: 100\theta_\mathrm{MC}
    prior:
      max: 10
      min: 0.5
    proposal: 0.0002
    ref:
      dist: norm
      loc: 1.04109
      scale: 0.0004
    renames: theta
  w:
    latex: w_{0,\mathrm{DE}}
    prior:
      max: 1
      min: -3
    proposal: 0.02
    ref:
      dist: norm
      loc: -1.01
      scale: 0.02
  wa:
    latex: w_{a,\mathrm{DE}}
    prior:
      max: 2
      min: -3
    proposal: 0.05
    ref:
      dist: norm
      loc: 0
      scale: 0.05
  zre:
    latex: z_\mathrm{re}
sampler:
  mcmc:
    covmat: auto
    drag: true
    oversample_power: 0.4
    proposal_scale: 1.9
output: Planck_BAO_SN_CPL

```
