### ISSUE TITLE
MCMC with MPI give identical chains

### ISSUE THREAD

**Issue by louisl3grand** [CobayaSampler/cobaya#172]
I am using Cobaya with a custom likelihood and I am trying to sample it using a MCMC with MPI.

My issue is that each process samples the same points of the likelihood in the same order, i.e. the output files likelihood.x.txt are all identicals.
The starting points are defined with a uniform PDF, but it appears that all my chains have the same starting point. If I understand correctly, each process is a different chain, so I would expect them to take a different starting  point.

I am using mpi4py 3.0.3 with python 3.9.2.

Here is the params section of my likelihood file

```
params:
  Alens:
    prior:
      min: 0.9
      max: 1.1
    ref: 
      min: 0.95
      max: 1.05
    latex: A_\mathrm{lens}

  # Planck 2018 Plik best fit:
  ombh2: 0.022383
  omch2: 0.12011
  theta_MC_100: 
    value: 1.040909
    drop: true
  cosmomc_theta:
    value: 'lambda theta_MC_100: 1.e-2*theta_MC_100'
    derived: false
  tau: 0.0543
  logA: 
    value: 3.0448
    drop: true
  As:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
  ns: 0.96605
  mnu: 0.06
  nnu: 3.046

sampler:
  mcmc:
    max_samples: .inf
```

Here is in an extract of the Cobaya logs
```
[0 : model] Measuring speeds... (this may take a few seconds)
[0 : model] Setting measured speeds (per sec): {opticpp.cobaya.lensing_like.LensingLike: 0.395, camb.transfers: 0.289, camb: 0.289}
[0 : mcmc] Covariance matrix not present. We will start learning the covariance of the proposal earlier: R-1 = 30 (would be 2 if all params loaded).
[0 : mcmc] Initial point: Alens:0.9749727
[2 : mcmc] Initial point: Alens:0.9749727
[3 : mcmc] Initial point: Alens:0.9749727
[1 : mcmc] Initial point: Alens:0.9749727
[0 : mcmc] Sampling!
[1 : mcmc] Progress @ 2021-05-04 18:25:07 : 1 steps taken, and 0 accepted.
[2 : mcmc] Progress @ 2021-05-04 18:25:07 : 1 steps taken, and 0 accepted.
[3 : mcmc] Progress @ 2021-05-04 18:25:07 : 1 steps taken, and 0 accepted.
[0 : mcmc] Progress @ 2021-05-04 18:25:07 : 1 steps taken, and 0 accepted.
```
