### ISSUE TITLE
how do i set   fluid_equation_of_state correctly in the .yaml file?

### ISSUE THREAD

**Issue by Rockdeldiablo** [CobayaSampler/cobaya#220]
i have a local installation of class which has been modified to include a linear redshift model (LRS) and a squared redshift model (SRS).
Everythings seems to work when i  type ./class testlrs.ini but when i try to use jupyter+cobaya together with my definition of dark energy model i get an error.
As an example, i used cobaya-cosmo-generator to generate  a cosmo-g.yaml file for a clp model  and then i modified it by including the line
`  fluid_equation_of_state: LRS`

The result looks like this
```

theory:
  classy:
    path: /home/pasquale/Documenti/class_public/
    extra_args:
      N_ncdm: 1
      N_ur: 2.0328
likelihood:
  sn.pantheon: null
params:
  logA:
    prior:
      min: 1.61
      max: 3.91
    ref:
      dist: norm
      loc: 3.05
      scale: 0.001
    proposal: 0.001
    latex: \log(10^{10} A_\mathrm{s})
    drop: true
  A_s:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
  n_s:
    prior:
      min: 0.8
      max: 1.2
    ref:
      dist: norm
      loc: 0.965
      scale: 0.004
    proposal: 0.002
    latex: n_\mathrm{s}
  theta_s_1e2:
    prior:
      min: 0.5
      max: 10
    ref:
      dist: norm
      loc: 1.0416
      scale: 0.0004
    proposal: 0.0002
    latex: 100\theta_\mathrm{s}
    drop: true
  100*theta_s:
    value: 'lambda theta_s_1e2: theta_s_1e2'
    derived: false
  H0:
    latex: H_0
  omega_b:
    prior:
      min: 0.005
      max: 0.1
    ref:
      dist: norm
      loc: 0.0224
      scale: 0.0001
    proposal: 0.0001
    latex: \Omega_\mathrm{b} h^2
  omega_cdm:
    prior:
      min: 0.001
      max: 0.99
    ref:
      dist: norm
      loc: 0.12
      scale: 0.001
    proposal: 0.0005
    latex: \Omega_\mathrm{c} h^2
  Omega_m:
    latex: \Omega_\mathrm{m}
  omegamh2:
    derived: 'lambda Omega_m, H0: Omega_m*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  m_ncdm:
    value: 0.06
    renames: mnu
  w0_fld:
    prior:
      min: -3
      max: 1
    ref:
      dist: norm
      loc: -0.99
      scale: 0.02
    proposal: 0.02
    latex: w_{0,\mathrm{DE}}
  wa_fld:
    prior:
      min: -3
      max: 2
    ref:
      dist: norm
      loc: 0
      scale: 0.05
    proposal: 0.05
    latex: w_{a,\mathrm{DE}}
  Omega_Lambda: 0
  fluid_equation_of_state: LRS
  YHe:
    latex: Y_\mathrm{P}
  tau_reio:
    prior:
      min: 0.01
      max: 0.8
    ref:
      dist: norm
      loc: 0.055
      scale: 0.006
    proposal: 0.003
    latex: \tau_\mathrm{reio}
  z_reio:
    latex: z_\mathrm{re}
sampler:
  mcmc:
    covmat: auto

```
Initially i thought there was something wrong with my definition LRS but then i tested   `fluid_equation_of_state: CLP` and it also fail:

[tools] *ERROR* Failed to load external function: 'NameError("name 'CLP' is not defined")'

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.9/site-packages/cobaya/tools.py in get_external_function(string_or_function, name)
    374             with PythonPath(os.curdir, when="import_module" in string_or_function):
--> 375                 function = eval(string_or_function, scope)
    376         except Exception as e:

~/anaconda3/lib/python3.9/site-packages/cobaya/tools.py in <module>

> NameError: name 'CLP' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> LoggedError                               Traceback (most recent call last)
> /tmp/ipykernel_4970/93674339.py in <module>
>       5 from cobaya.run import run
>       6 
> ----> 7 updated_info, sampler = run(info_from_yaml)
> 
> ~/anaconda3/lib/python3.9/site-packages/cobaya/run.py in run(info_or_yaml_or_file, packages_path, output, debug, stop_at_error, resume, force, no_mpi, test, override)
>     132                 out, info=updated_info["sampler"][sampler_name])
>     133             # 4. Initialize the posterior and the sampler
> --> 134             with Model(updated_info["params"], updated_info["likelihood"],
>     135                        updated_info.get("prior"), updated_info.get("theory"),
>     136                        packages_path=info.get("packages_path"),
> 
> ~/anaconda3/lib/python3.9/site-packages/cobaya/model.py in __init__(self, info_params, info_likelihood, info_prior, info_theory, packages_path, timing, allow_renames, stop_at_error, post, skip_unused_theories, dropped_theory_params)
>     141             if v not in (None, {}):
>     142                 self._updated_info[k] = deepcopy_where_possible(v)  # type: ignore
> --> 143         self.parameterization = Parameterization(self._updated_info["params"],
>     144                                                  allow_renames=allow_renames,
>     145                                                  ignore_unused_sampled=post)
> 
> ~/anaconda3/lib/python3.9/site-packages/cobaya/parameterization.py in __init__(self, info_params, allow_renames, ignore_unused_sampled)
>     144                 else:
>     145                     self._input[p] = np.nan
> --> 146                     self._input_funcs[p] = get_external_function(info["value"])
>     147                     self._input_args[p] = getfullargspec(self._input_funcs[p]).args
>     148             if is_sampled_param(info):
> 
> ~/anaconda3/lib/python3.9/site-packages/cobaya/tools.py in get_external_function(string_or_function, name)
>     375                 function = eval(string_or_function, scope)
>     376         except Exception as e:
> --> 377             raise LoggedError(
>     378                 log, "Failed to load external function%s: '%r'",
>     379                 " '%s'" % name if name else "", e)
> 
> LoggedError: Failed to load external function: 'NameError("name 'CLP' is not defined")'

so i think there is something wrong with the .yaml file itself. Any advice?
