### ISSUE TITLE
Wrong derived parameters when removing and adding the same likelihood in post-processing

### ISSUE THREAD

**Issue by zhaoruiyang98** [CobayaSampler/cobaya#285]
Hi all,

I want to do a post-processing to force-recompute the likelihood to get extra derived parameters, however I find the new computed derived parameters are possible to be wrong. Here I'm attaching the minimum example to reproduce this issue:

```python
# gauss.py
import numpy as np
from cobaya.likelihood import Likelihood


class Gauss(Likelihood):
    def initialize(self):
        self.mean = np.array([0, 0])
        self.cov = np.array([[1, 1], [1, 4]])
        self.invcov = np.linalg.inv(self.cov)

    def get_requirements(self):
        return ["a", "b"]

    def get_can_provide_params(self):
        return ["one", "two"]

    def calculate(self, state, want_derived=True, **params_values_dict):
        a, b = params_values_dict["a"], params_values_dict["b"]
        theory = np.array([a, b])
        res = theory - self.mean
        state["logp"] = -0.5 * (res @ self.invcov @ res)
        if want_derived:
            state["derived"]["one"] = 1
            state["derived"]["two"] = 2

```

```yaml
# Gauss.yaml
# empty
```

```yaml
# test.yaml
likelihood:
  gauss.Gauss:
    python_path: "."
params:
  a:
    prior:
      min: -100
      max: 100
    ref: 0.0
    proposal: 0.1
    latex: a
  b:
    prior:
      min: -100
      max: 100
    ref: 0.0
    proposal: 0.1
    latex: b
  one:
sampler:
  mcmc:
    Rminus1_stop: 0.01
output: chains/test
```

```yaml
# post.yaml
post:
  suffix: two
  add:
    likelihood:
      gauss.Gauss:
        python_path: "."
    params:
      # one:
      two:
  remove:
    likelihood:
      gauss.Gauss:
    # params:
    #   one:
output: chains/test
```

I just run `cobaya-run test.yaml` and then `cobaya-run post.yaml`, the expected behaviour is I would get `two=2`, however I obtained `two=1`. I find this is possibly related to [this line](https://github.com/CobayaSampler/cobaya/blob/91cd720403ad6f734d5a08198809f637e2db7b18/cobaya/post.py#L463), `model_add.output_params` contains only `one` while `output_derived` contains two values.
A possible workaround is removing and adding parameter `one`, but it would be cumbersome if I have many derived parameters before...
