### ISSUE TITLE
Speed blocking in PolyChord reduces ints by common denominator

### ISSUE THREAD

**Issue by lukashergt** [CobayaSampler/cobaya#35]
Hi Jesus,

when specifying the blocking option in the PolyChord sampler and providing integers for the speeds, e.g.

```yaml
sampler:
  polychord:
    blocking: 
      - [2, [omega_b, omega_cdm, H0, tau_reio, logA, n_s]]
      - [12, [A_planck]]
      - [50, [A_cib_217, xi_sz_cib, A_sz, ps_A_100_100, ps_A_143_143, ps_A_143_217, ps_A_217_217, ksz_norm, gal545_A_100, gal545_A_143, gal545_A_143_217, gal545_A_217, calib_100T, calib_217T]]
```
then these integers are divided by their common denominators before turning them into the number of repeats, i.e. in this case the integers `[2, 12, 50]` are first reduced to `[1, 6, 25]` and then multiplied by the number of parameters to give the number of repeats for PolyChord `[6, 6, 350]`. The parameter `num_repeats` seems to be ignored entirely when `blocking` is specified.

However, for accurate evidences the number of repeats of slow parameters should be greater than the number of slow parameters. Thus, there should be no reduction of speeds by common denominators for PolyChord. 

An easy workaround is to choose integers with no common denominators (e.g. go for 51 instead of 50 here), but I thought I should report the issue here nonetheless.

Best,
Lukas
