### ISSUE TITLE
Sampling over HMCode params

### ISSUE THREAD

**Issue by fbianchini** [CobayaSampler/cobaya#369]
Hi there, 

I would like to run a chain using CAMB as theory engine while marginalizing over one of the non-linear P(k) parameters in the `mead2020_feedback` model, specifically `HMCode_logT_AGN `.

I added the following to the param block
```
params:
  HMCode_logT_AGN:
    latex: \log(T_{\mathrm{AGN}})
    max: 8.5
    min: 7.1
```
and set the theory block to 
```
theory:
  camb:
    extra_args:
      AccuracyBoost: 1
      bbn_predictor: PArthENoPE_880.2_standard.dat
      halofit_version: mead2020_feedback
      lAccuracyBoost: 1
      lSampleBoost: 1
      lens_margin: 1250
      lens_potential_accuracy: 4
      nnu: 3.046
      num_massive_neutrinos: 1
      theta_H0_range:
      - 40
      - 100
```
However, when I submit the job, cobaya throws the following error
`[model] *ERROR* Could not find whom to assign output parameters ['HMCode_logT_AGN'].`

I suspect the issue might be related to the configuration of the HMCode_logT_AGN parameter or its integration with CAMB. Any guidance or pointers on how to resolve this error would be greatly appreciated.

Thanks!
