### ISSUE TITLE
Modified CLASS not found

### ISSUE THREAD

**Issue by ark93-cosmo** [CobayaSampler/cobaya#397]
Hello,
I cloned the latest [AxiCLASS version](https://github.com/PoulinV/AxiCLASS/tree/master) and compiled it using:
`PYTHON=/path/to/cobaya/bin/python make clean; make all`, as suggested [here](https://cosmocoffee.info/viewtopic.php?p=10262&hilit=Could+not+find+CLASS%3A+cobaya#p10262)
Here's the theory part of my yaml file:
```
theory:
  classy:
    extra_args:
      precision_loop_over_background: 0.001
      background_Nloga: 1000000.0
      scf_has_perturbations: ye
      N_ur: 0.00441
      attractor_ic_scf: n
      do_shooting_scf: ye
      scf_tuning_index: 0
      running_cobaya: 'yes'
      n_axion: 3
      non linear: halofit
      scf_potential: axion
      deg_ncdm: 3
      n_axion_security: 2.09
      use_big_theta_scf: ye
      do_shooting: ye
      security_small_Omega_scf: 0.001
      compute damping scale: ye
      N_ncdm: 1
      scf_thetadot_ini_cobaya: 0
    ignore_obsolete: true
    path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/
```
Nevertheless, COBAYA is still loading the original classy. Here's the log output:
```
[0 : output] Output to be read-from/written-into folder '/automnt/path/to/cobaya/Extended_Models/EDE/Plk', with prefix 'CLASS'
[0 : output] Found existing info files with the requested output prefix: '/automnt/path/to/cobaya/Extended_Models/EDE/Plk/CLASS'
[0 : output] Will delete previous products ('force' was requested).
[0 : prior] *WARNING* External prior 'SZ' loaded. Mind that it might not be normalized!
[2 : classy] *ERROR* Could not find CLASS: Could not import 'classy' from /automnt/path/to/cobaya/Codes/code/AxiCLASS/: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310. To install it, run `cobaya-install classy`
[0 : classy] *ERROR* Could not find CLASS: Could not import 'classy' from /automnt/path/to/cobaya/Codes/code/AxiCLASS/: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310. To install it, run `cobaya-install classy`
[4 : classy] *ERROR* Could not find CLASS: Could not import 'classy' from /automnt/path/to/cobaya/Codes/code/AxiCLASS/: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310. To install it, run `cobaya-install classy`
[6 : classy] *ERROR* Could not find CLASS: Could not import 'classy' from /automnt/path/to/cobaya/Codes/code/AxiCLASS/: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310. To install it, run `cobaya-install classy`
[5 : classy] *ERROR* Could not find CLASS: Could not import 'classy' from /automnt/path/to/cobaya/Codes/code/AxiCLASS/: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310. To install it, run `cobaya-install classy`
[7 : classy] *ERROR* Could not find CLASS: Could not import 'classy' from /automnt/path/to/cobaya/Codes/code/AxiCLASS/: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310. To install it, run `cobaya-install classy`
[1 : classy] *ERROR* Could not find CLASS: Could not import 'classy' from /automnt/path/to/cobaya/Codes/code/AxiCLASS/: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310. To install it, run `cobaya-install classy`
[3 : classy] *ERROR* Could not find CLASS: Could not import 'classy' from /automnt/path/to/cobaya/Codes/code/AxiCLASS/: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310. To install it, run `cobaya-install classy`
[7 : exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/path/to/cobaya/lib/python3.10/site-packages/cobaya/component.py", line 755, in _bare_load_external_module
    return load_module(name, path=import_path, min_version=min_version,
  File "/path/to/cobaya/lib/python3.10/site-packages/cobaya/tools.py", line 193, in load_module
    check_module_path(module, path)
  File "/path/to/cobaya/lib/python3.10/site-packages/cobaya/tools.py", line 136, in check_module_path
    raise ModuleNotFoundError(
ModuleNotFoundError: Module classy successfully loaded, but not from requested path: /automnt/path/to/cobaya/Codes/code/AxiCLASS/python/build/lib.linux-x86_64-cpython-310, but instead from /automnt/path/to/cobaya/Codes/code/classy/python/build/lib.linux-x86_64-cpython-310

```
I must have missed a very simple step somewhere, but I think I'm doing exactly what I did in previous versions of COBAYA.
Is there a specific .pth file from which cobaya gets paths? What's weird is that COBAYA is detecting the correct path, but still loading the original classy version.
Appreciate the help!

**Comment by JesusTorrado** [comment]
Hi @ark93-cosmo 

It seems that you are not passing the actual path to your local CLASS install, but a placeholder instead. Does your CLASS files show up when you do `/automnt/path/to/cobaya/Codes/code/AxiCLASS/` in a terminal?

**Comment by ark93-cosmo** [comment]
Hi @JesusTorrado 
Thank you for the reply!
I'm pretty sure I'm using the actual path to where AxiCLASS is installed. If I go to that directory and do `pwd`, I copy that path, which what I'm putting in the 
```
theory:
  classy:
    extra_args:
      path:
```
Should I add this path to some file which COBAYA uses to find paths?
