### ISSUE TITLE
Scalar field Issue

### ISSUE THREAD

**Issue by sonejalam** [CobayaSampler/cobaya#411]
Hi..I am using cobaya first time to run scalar field as a dark energy and this is my .yaml file for scalar field
```
theory:
  classy:
    path: /mnt/home/project/csonej/class_public-master
    extra_args:
      non linear: hmcode
      nonlinear_min_k_max: 20
      N_ncdm: 1
      N_ur: 2.0328
      attractor_ic_scf: no
      scf_tuning_index: 0

scf_parameters__1:
    prior:
      min: -0.3
      max: 0.5
    ref:
      dist: norm
      loc: 0.1
      scale: 0.01
    proposal: 0.01
  scf_parameters__2:
    prior:
      min: 0.2
      max: 1.
    ref:
      dist: norm
      loc: 0.7
      scale: 0.01
    proposal: 0.01
  scf_parameters__3:
    prior:
      min: 0.
      max: 30
    ref:
      dist: norm
      loc: 2
      scale: 0.01
    proposal: 0.01
  scf_parameters__4:
    prior:
      min: 0
      max: 15
    ref:
      dist: norm
      loc: 11
      scale: 0.5
    proposal: 0.01

  scf_parameters__5:
    prior:
      min: -0.3
      max: 0.3
    ref:
      dist: norm
      loc: 0.05
      scale: 0.01
    proposal: 0.01
  scf_parameters__6:
    prior:
      min: 0.1
      max: 1.5
    ref:
      dist: norm
      loc: 0.3
      scale: 0.01
    proposal: 0.01

  scf_parameters__7:
    prior:
      min: 0.
      max: 1e-10
    ref:
      dist: norm
      loc: 1e-12
      scale: 1e-16
    proposal: 1e-16
  
  Omega_scf:
    value: 0.7
```
 it will not recognising the scf parameters  whereas the montepython is working well for this model
So please give me the suggestion to run it
