### ISSUE TITLE
Persistent MCMC Chain Stalling with Cobaya 2.0.3 in Python 3.9 Environment (pyenv) - Even with Simplified Models

### ISSUE THREAD

**Issue by maurydc** [CobayaSampler/cobaya#413]
**Describe the bug**
We are encountering persistent MCMC chain stalling issues when running Cobaya 2.0.3 within a Python 3.9 environment managed by `pyenv` on an Ubuntu 22.04 system. The chain typically starts, takes a few steps (1-3 samples), and then stops with the error: `[mcmc] *ERROR* The chain has been stuck for -X attempts. Stopping sampling.` This occurs even with highly simplified cosmological models and minimal likelihoods.

**To Reproduce**

1.  **Environment Setup:**
    *   Ubuntu 22.04 (amd64 sandbox environment).
    *   Python 3.9.19 installed via `pyenv` (initially with `--enable-shared` to attempt to solve header issues for `clik`, though `clik` compilation ultimately failed and was bypassed).
    *   Cobaya 2.0.3 installed via `pip install git+https://github.com/CobayaSampler/cobaya.git@2.0.3`.
    *   CLASS (cosmological Boltzmann code) cloned from `git clone https://github.com/lesgourg/class_public.git`, compiled (`make libclass.a && make classy`), and `classy` wrapper installed in the Python 3.9 environment.
    *   NumPy downgraded to `1.23.5` to resolve `np.float` errors with Cobaya 2.0.3.
    *   Dependencies like `getdist`, `matplotlib`, `gfortran`, `liblapack-dev`, `libblas-dev` were also installed.

2.  **YAML Configuration (Example of an ultra-simplified model that still stalls):**
    *   File: `wcdm_alt_likelihood_config.yaml` (can be provided if requested)
    *   This configuration uses only `w0_fld` and `H0` as free parameters, with all other cosmological parameters fixed. It uses the `H0.riess2018b` likelihood, which does not require external compilation.

    ```yaml
    # Versão com likelihood H0 alternativo
    debug: True

    # Código teórico (CLASS padrão)
    theory:
      classy:
        extra_args:
          output: "mPk"
          P_k_max_1/Mpc: 10

    # Mantendo apenas dois parâmetros livres
    params:
      # Equação de estado da energia escura
      w0_fld:
        prior:
          min: -2.0
          max: -0.1
        ref: -1.0
        proposal: 0.05
        latex: w_0

      # Constante de Hubble
      H0:
        prior:
          min: 60
          max: 80
        ref: 73.0
        proposal: 0.8
        latex: H_0

      # Parâmetros fixos
      Omega_fld:
        value: 0.68
        latex: \Omega_{\mathrm{DE}}

      omega_b:
        value: 0.0224
        latex: \omega_b

      omega_cdm:
        value: 0.12
        latex: \omega_{cdm}
        
      A_s:
        value: 2.1e-9
        latex: A_s
        
      n_s:
        value: 0.965
        latex: n_s
        
      tau_reio:
        value: 0.054
        latex: \tau_{\mathrm{reio}}

    likelihood:
      H0.riess2018b: null

    sampler:
      mcmc:
        max_samples: 5000
        learn_proposal: True
        Rminus1_stop: 0.05
        burn_in: 0.5
        check_every: 500
        max_tries: 100000
        proposal_scale: 1.8
        callback_every: 100

    output: "/home/ubuntu/cobaya_runs/wcdm_alt_likelihood/wcdm_alt_likelihood"
    force: True
    ```

3.  **Execution Command:**
    `cobaya-run /path/to/wcdm_alt_likelihood_config.yaml`

**Expected behavior**
The MCMC chain should run for the specified `max_samples` or until convergence criteria are met.

**Actual behavior**
The chain starts, typically processes 1-3 samples, and then outputs the "chain has been stuck" error, stopping the sampling. This behavior was consistent across various configurations, including more complex models (wCDM with more free parameters) and different H0 likelihoods (`H0.riess201903`).

**Troubleshooting Steps Taken (Summary - full details in attached README.md):**

*   Ensured Python 3.9 environment with compatible NumPy (1.23.5).
*   Successfully compiled and installed CLASS and `classy`.
*   Experimented extensively with `ref` and `proposal` values for all parameters.
*   Adjusted MCMC sampler settings (`max_tries`, `proposal_scale`, `Rminus1_stop`, `burn_in`, `check_every`).
*   Progressively simplified the model, reducing free parameters to just two (`w0_fld`, `H0`).
*   Switched between `H0.riess201903` and `H0.riess2018b` likelihoods.
*   Attempted to resolve issues with `modules` path vs. explicit likelihood data paths (though this became less relevant when bypassing Planck likelihoods due to `clik` compilation failures).
*   The `clik` compilation for Planck likelihoods failed due to missing `Python.h` headers, despite attempts to install `python3.9-dev` equivalents in a `pyenv` setup (this is a secondary issue but part of the overall environment challenge).

**Hypotheses:**

*   Potential issue with Cobaya 2.0.3's MCMC sampler in this specific environment configuration.
*   Interaction problem between Cobaya 2.0.3, CLASS, and the simple H0 likelihoods used.
*   Underlying limitation or instability within the sandboxed Ubuntu 22.04 environment affecting Cobaya's execution.

**Additional context**
We have a detailed `README.md` summarizing all attempts and configurations, and the various YAML files used. We can provide these if helpful.
```

<!-- Failed to upload "readme_erro_cosmologico.md" -->
