### ISSUE TITLE
Stuck after resuming

### ISSUE THREAD

**Issue by eelregit** [CobayaSampler/cobaya#415]
Dear Cobaya dev,

This is something that has puzzled us for many days now:

To workaround [a memory leak in our CLASS mod](https://github.com/lesgourg/class_public/compare/0ceb7a9...paulomontero:class_gomp:e0f8daa) which we failed to bebug, we uses a slurm script to endlessly loop over a job step that lasts 8 hours every time (see below for the script). However, another problem arises, in some chains the walkers tend to get stuck after resuming, for both serial and parallel jobs. It feels like the resuming is incomplete, or the resumed state is different, or almost as if the MCMC sampler is not Markovian.

Does this ring a bell? Any suggestions would be greatly appreciated!

Our job scripts look like this
```bash
...

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

...

while true
do
  srun --mem=0 --time=08:00:00 cobaya run --resume --allow-changes cobaya.yaml
done
```

and yaml file:
```yaml
sampler:
  mcmc:
    oversample_power: 0.4
    learn_proposal_Rminus1_max: 30
    covmat: auto
    Rminus1_stop: 0.01
    Rminus1_cl_stop: 0.2

...
```
