### ISSUE TITLE
Modernize codebase: Python 3.10+ with ruff formatting

### ISSUE THREAD

**Issue by cmbant** [CobayaSampler/cobaya#418]
This is a comprehensive modernization of the Cobaya codebase to use Python 3.10+ and ruff for formatting and linting.

## Summary of Changes

This modernization includes:

1. **Python Version Update**: Minimum version updated from 3.8+ to 3.10+
2. **Code Modernization**: Applied pyupgrade to use modern Python 3.10+ syntax
3. **Ruff Integration**: Replaced flake8 with ruff for linting and formatting
4. **Pre-commit Hooks**: Added automated code quality checks
5. **Development Tools**: Updated documentation and added VSCode configuration
6. **Build Improvements**: Updated to build wheels instead of just source distributions

## Files Changed

- **pyproject.toml**: Updated Python version requirements, added ruff configuration, added devel dependencies
- **DEVEL.rst**: Updated development documentation with ruff instructions
- **.pre-commit-config.yaml**: New file with pre-commit hooks
- **.vscode/settings.json**: New VSCode configuration for ruff integration
- **.gitignore**: Enhanced to include Python development artifacts
- **tests-environment.yml**: Replaced flake8 with ruff
- **All Python files**: Formatted with ruff and modernized with pyupgrade

## GitHub Workflow Changes Needed

Due to OAuth restrictions, the workflow file couldn't be updated automatically. Please apply these changes to `.github/workflows/tests.yml`:

1. **Update Python version** (line 60-64):
   ```yaml
   - name: "OS X Python 3.10 (with classy)"
     os: macos-latest
     python-version: "3.10"
     mpi: openmpi
     cobaya_skip: polychord
   ```

2. **Replace flake8 with ruff** (lines 99-104):
   ```yaml
   - name: Ruff Lint
     if: matrix.pydist == 'ANACONDA'
     shell: bash -el {0}
     run: |
       pip install ruff
       ruff check cobaya/ tests/ --output-format=github
   ```

3. **Build wheels instead of just source** (line 183):
   ```yaml
   - name: Build package
     run: python -m build
   ```

## Installation for Developers

After applying these changes, developers should:

```bash
# Install development dependencies
pip install -e .[devel]

# Set up pre-commit hooks
pre-commit install

# Run formatting and linting
ruff check --fix cobaya/ tests/
ruff format cobaya/ tests/
```

## Ruff Configuration

The ruff configuration in pyproject.toml includes:
- Line length: 90 characters
- Target Python version: 3.10+
- Selected lint rules matching the previous flake8 configuration
- Double quotes for strings
- Space indentation

This modernization maintains backward compatibility while bringing the codebase up to modern Python standards and improving the development experience.

---

*This issue was created by AI following a comprehensive modernization plan. The changes are ready for review and application.*
