### ISSUE TITLE
Unable to resume chains

### ISSUE THREAD

**Issue by msyriac** [CobayaSampler/cobaya#74]
I'm trying to resume a chain but I get the following error:
```
[0 : input] is_equal_info: different [theory] or different order of them: ['camb', 'camb.transfers'] vs ['camb']                                     
[0 : output_mpi] *ERROR* Old and new sample information not compatible! Resuming not possible! 
```

This happens despite the fact that the exact same script with the same arguments is run. In particular, the theory section of the info dictionary looks like this:
```
'theory': {"camb": {'stop_at_error': False,'speed': 0.6,                                                                                         
                        "extra_args": {'halofit_version': 'mead', 'nnu': 3.046,                                                                      
                                       'num_massive_neutrinos': 3, 'cosmomc_theta': None,                                                            
                                       "nonlinear": True, "kmax": 5., "dark_energy_model": "ppf",                                                    
                                       'NonLinear': model.NonLinear_both, "WantTransfer": True}}}
```
and has not changed between resuming. I'm working on the devel branch.

**Comment by cmbant** [comment]
Was the original chain run with the same cobaya git head? camb.transfers should not be in the updated.yaml produced in the original run, and doesn't seem to appear in chains produced by the current devel head.

**Comment by cmbant** [comment]
A conflict between the recent version and HelperTheory changes.  This should fix it: https://github.com/CobayaSampler/cobaya/commit/da86390b5c580b5431b238fcaa062cb5f7fa094f

**Comment by msyriac** [comment]
I've updated my devel branch, re-installed and confirmed that the changes appear in the python package directory, but I get the same error as before.

**Comment by cmbant** [comment]
Can you share your updated.yaml (regengerated with the new version)

**Comment by msyriac** [comment]
I've attached the updated.yaml generated after re-installing and re-submitting in this pastebin:
https://pastebin.com/ptjNB3jn

**Comment by cmbant** [comment]
Thanks. Hmm, looks the same as before the change. Was generated from scratch with a clean chain root using the new version? In my local test camb.transfers is not produced in the updated.yaml after the update commit. I may need a more complete test cast to reproduce.

**Comment by msyriac** [comment]
"from scratch with a clean chain root using the new version?"
No, I'm trying to resume a production run that I already have saved and ran for four hours. That run was started before the update. Do you think it will be possible to resume it at all without extensive hacking?

**Comment by msyriac** [comment]
To clarify: the updated.yaml is from the chain directory after trying to resume an old run (pre-update) with a new run with the resume=True option post-update.

**Comment by cmbant** [comment]
Ah, good. Yes, just delete the camb.transfers section in the updated.yaml.

**Comment by msyriac** [comment]
Ok, great, that solves that! But now we have a new problem:
```
[output_mpi] Found existing products with the requested output prefix: '/scratch/r/rbond/msyriac/data/depot/chains/test_try61_newcosmo_omar_retry_mean_bao/'
[output_mpi] Let's try to resume/load.
[exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.1.0-py3.6.egg/cobaya/tools.py", line 202, in get_class
    return return_class(internal_module, package=_package)
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.1.0-py3.6.egg/cobaya/tools.py", line 185, in return_class
    _module = load_module(_module_name, package=package, path=module_path)
  File "/home/r/rbond/msyriac/.local/lib/python3.6/site-packages/cobaya-2.1.0-py3.6.egg/cobaya/tools.py", line 143, in load_module
    module = import_module(name, package=package)
  File "/scinet/niagara/intel/2018.2/intelpython3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cobaya.likelihoods.sclnlike'
```

sclnlike is the name of the external likelihood function I'm using. It is defined in the script that I run.

The relevant part of updated.yaml is:
```
likelihood:                                                                                                                                                                                   
  sclnlike:                                                                                                                                                                                   
    external: true                                                                                                                                                                            
    input_params:                                                                                                                                                                             
    - Pshot                                                                                                                                                                                   
    - b                                                                                                                                                                                       
    output_params: []                                                                                                                                                                         
    speed: 0.003                                                                                                                                                                              
    stop_at_error: false                                                                                                                                                                      
    version: null                                                                                                                                                                             
  bao.sdss_dr12_consensus_bao:                                                                                                                                                                
    speed: 0.0005                                                                                                                                                                             
    stop_at_error: false                                                                                                                                                                      
    version: null                                                                                                                                                                             
    path: /home/r/rbond/msyriac/repos/mock_likelihoods/                                                                                                                                       
    measurements_file: bao_data/sdss_DR12Consensus_bao.dat                                                                                                                                    
    cov_file: bao_data/BAO_consensus_covtot_dM_Hz.txt                                                                                                                                         
    rs_fid: 147.78                                                                                                                                                                            
    alises:                                                                                                                                                                                   
    - BAO                                                                                                                                                                                     
    input_params: []                                                                                                                                                                          
    output_params: []              
```

The relevant part in the script I run is:
```
def sclnlike(b, Pshot,                                                                                                                                                                        
             _theory = {'source_Cl':                                                                                                                                                          
                        {'sources': {'W1':{'function': 'spline', 'source_type': 'counts', 'bias': default_bias,'z':z,'W':W}},                                                                 
                         'limber': True, 'lmax': lmax,'non_linear': True}},                                                                                                                   
             **source_params):                                                                                                                                                                
              # stuff
              ...

                                


info = {'timing':True, 'resume': True,                                                                                                                                                                        
    'params': { \                                                                                                                                                                             
                'ombh2': iparams['ombh2'], 'tau': iparams['tau'],'ns':iparams['ns'],'mnu': iparams['mnu'],                  "sigma8": {"derived": True, "latex": r"\sigma_8"},                                                                                                                            
                "omegam": {"derived": True, "latex": r"\Omega_{m}"},                                                                                                                          
                "logA": {"prior": {"min": 1.5, "max": 4.2},'drop':True,'ref':{'dist': 'norm', "loc": 3.091, "scale": 0.1},"latex":r"\rm{ln}10^{10}A_s"}, # 3.091                              
                "As":{"value": "λ logA: 1e-10*np.exp(logA)","latex": "A_\mathrm{s}"},                                                                                                         
                "omch2": {"prior": {"min": 0.005, "max": 0.99}, "latex": r"\Omega_{c}h^2",'ref':{'dist': 'norm', "loc": 0.1198, "scale": 0.2*0.1198}},                                        
                "H0": {"prior": {"min": myclip_a, "max": myclip_b}, "latex": r"H_0",'ref':{'dist': 'norm', "loc": 67.0, "scale": 8.0}},                                                                                                                                                                    
                "Pshot": {"prior": {'dist': 'norm', "loc": pshot_def, "scale": 0.5*pshot_def}, "latex": r"P_{\rm shot}",'ref':{'dist': 'norm', "loc": pshot_def, "scale": 0.1*pshot_def}},    
                "b": {"prior": {"min": 0.5, "max": 3.5}, "latex": r"b",'ref':{'dist': 'norm', "loc": 2.0, "scale": 0.2}}},                                                                    
        'likelihood': {'sclnlike':{'external':sclnlike, 'speed':0.003}                                                                                                                        
                       },                                                                                                                                                                     
    'theory': {"camb": {'stop_at_error': False,'speed': 0.6,                                                                                                                                  
                        "extra_args": {'halofit_version': 'mead', 'nnu': 3.046,                                                                                                               
                                       'num_massive_neutrinos': 3, 'cosmomc_theta': None,                                                                                                     
                                       "nonlinear": True, "kmax": 5., "dark_energy_model": "ppf",                                                                                             
                                       'NonLinear': model.NonLinear_both, "WantTransfer": True}}},                                                                                            
        'sampler': {'mcmc': {"burn_in": 100, "max_samples": np.inf, "max_tries": 400, "learn_proposal": True,'drag':not(args.no_drag)}},                                                      
                                              'output': f'{rdir}/{oversion}/'}  
```
