### ISSUE TITLE
Cosmomc equivalent parameter specification / Gaussian prior + bound

### ISSUE THREAD

**Issue by msyriac** [CobayaSampler/cobaya#80]
I'm trying to set up a cobaya run that's equivalent to a previous cosmomc run. Cosmomc lets you specify both bounds for a parameter as well as a Gaussian prior (I think), like this:
```
param[tau] = 0.09 0.01 0.8 0.01 0.005
prior[tau] = 0.065 0.015
```

What I have for the cobaya param equivalent is:
```
tau:                                                                                                                              
  prior:                                                                                                                        
    min: 0.01                                                                                                                   
    max: 0.8                                                                                                                    
  ref:                                                                                                                            
    dist: norm
    loc:   0.09
    scale: 0.01
  proposal: 0.005  
```
but it wasn't obvious to me how to add on the Gaussian prior `prior[tau] = 0.065 0.015` without removing the min-max bound. More generally, is it possibly to simultaneously specify a Gaussian prior as well as a top-hat bound for a parameter?
(Note that in the above example, the min-max bound is probably not needed at all, but there are many cases where a truncated Gaussian might be desirable)

**Comment by cmbant** [comment]
Probably the best way is to give a flat min,max prior on the parameter, and then add a separate prior to the priors block for the Gaussian.

Otherwise I guess [truncnorm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.truncnorm.html) work work, if not very efficiently.

**Comment by JesusTorrado** [comment]
Just to clarify: "not very efficiently" there means an overhead of ~10^{-2} sec instead of <10^3, which will be mostly unnoticeable if your chain needs to compute any power spectrum.

**Comment by JesusTorrado** [comment]
Actually, I just checked that `truncnorm` cannot be used directly. I will patch it tomorrow.

For now, I suggest defining a flat prior under `params`, and a gaussian under `prior` as

    prior:
      my_gaussian: "lambda p: stats.norm.logpdf(p, loc=mean, scale=std)"

where `p` is the name of your parameter.

**Comment by msyriac** [comment]
Thanks, both. Could you specify exactly how this 
" I suggest defining a flat prior under params, and a gaussian under prior as"
would be done for, e.g. this case:
```
tau:                                                                                                                              
  prior:                                                                                                                        
    min: 0.01                                                                                                                   
    max: 0.8                                                                                                                    
  ref:                                                                                                                            
    dist: norm
    loc:   0.09
    scale: 0.01
  proposal: 0.005  
```
with an additional Gaussian `prior[tau] = 0.065 0.015`?

**Comment by cmbant** [comment]
Something like (untested)
```
params:
...
 tau:                                                                                                                              
  prior:                                                                                                                        
    min: 0.01                                                                                                                   
    max: 0.8                                                                                                                    
  ref:                                                                                                                            
    dist: norm
    loc:   0.09
    scale: 0.01
  proposal: 0.005  
prior:
 tau_prior: "lambda tau: stats.norm.logpdf(tau, loc=0.065, scale=0.015)"
```

(we should perhaps rename "prior" as "priors" for consistency, since can be a list)
