### ISSUE TITLE
Strange Behavior w/ Blocking

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#89]
Hello,

I hope Jesus and Lewis are safe! I am testing the interface between Cobaya and Cosmolike - which has an internal caching. To allow for slow/fast I adopted the manual blocking

```
- [1, [logA, ns, theta_MC_100, omegabh2, omegach2]]
- [5, 
     [
       DES_DZ_L1, DES_DZ_L2, DES_DZ_L3, DES_DZ_L4, DES_DZ_L5, DES_B1_1,
       DES_B1_2, DES_B1_3, DES_B1_4, DES_B1_5, DES_DZ_S1, DES_DZ_S2, DES_DZ_S3, 
       DES_DZ_S4, DES_A1_1, DES_A1_2, DES_A2_1, DES_A2_2, DES_BTA_1
     ]
   ]
```

The strange behavior is that this only works if the order of parameters in the YAML file follows the block structure. If - for example, - I define the DES_M1 before DES_B1, then Cobaya does not split the blocks correctly. Another example - DES + Planck TT, if I define the DES likelihood first, 

  ```
des_y3.des_3x2pt:
    path: ./cobaya_modules/data/des_y3
  planck_2018_lowl.TT:
    path: ./cobaya_modules/
  planck_2018_lowl.EE:
    path: ./cobaya_modules/
  planck_2018_highl_plik.TTTEEE_lite:
    path: ./cobaya_modules/
  planck_2018_lensing.clik:
    path: ./cobaya_modules/
```

blocking works as expected. However, if I define Planck first

```
  planck_2018_lowl.TT:
    path: ./cobaya_modules/
  planck_2018_lowl.EE:
    path: ./cobaya_modules/
  planck_2018_highl_plik.TTTEEE_lite:
    path: ./cobaya_modules/
  planck_2018_lensing.clik:
    path: ./cobaya_modules/
  des_y3.des_3x2pt:
    path: ./cobaya_modules/data/des_y3
```

Then manual blocking fails to consider Planck parameters as fast. The reason is again related to the order that the default YAML of each likelihood is read. In the case of Planck + DES, the way I defined the blocking is shown below

```
blocking:      
  - [1, [logA, ns, theta_MC_100, omegabh2, omegach2]]
  - [5, 
        [
          DES_DZ_L1, DES_DZ_L2, DES_DZ_L3, DES_DZ_L4, DES_DZ_L5, DES_B1_1,
          DES_B1_2, DES_B1_3, DES_B1_4, DES_B1_5, DES_DZ_S1, DES_DZ_S2, DES_DZ_S3, 
          DES_DZ_S4, DES_A1_1, DES_A1_2, DES_A2_1, DES_A2_2, DES_BTA_1
        ]
    ]
  - [100, [DES_M1, DES_M2, DES_M3, DES_M4]]
  - [300, 
        [
           A_cib_217', 'gal545_A_217', 'calib_217T', 'galf_TE_A_217', 'ps_A_100_100', 
          'galf_TE_A_100_143', 'ps_A_217_217', 'ksz_norm', 'A_planck', 'calib_100T', 
          'ps_A_143_217', 'ps_A_143_143', 'gal545_A_100', 'galf_TE_A_143_217', 
          'gal545_A_143_217', 'galf_TE_A_100_217', 'galf_TE_A_143', 'gal545_A_143', 
          'xi_sz_cib', 'galf_TE_A_100', 'A_sz'
        ]
    ]
```
